### ISSUE TITLE
Implement Schedule DbApi Router API

### ISSUE THREAD

**Issue by russleyshaw** [siggame/coliselia#10]
File: `dbapi/src/routers/api/schedule.ts`

Implement an API router for schedules

NOTE: Query params, Params, and JSON Bodies should go through a jsonschema verification, so be sure to add the schema for each API endpoint

NOTE: Normal endpoints should not select for `data` and `result` columns. Specific endpoints will be provided

- [x] `GET /api/v2/schedule/` - get schedules from query params
- [x] `GET /api/v2/schedule/:id/` - get schedule from id
- [x] `POST /api/v2/schedule/` - create a schedule
- [x] `POST /api/v2/schedule/:id/` - update a schedule from id

- [x] `GET /api/v2/schedule/:id/data/` - get data json from schedule
- [x] `POST /api/v2/schedule/:id/data/` - set data json from schedule

- [x] `GET /api/v2/schedule/:id/result/` - get result json from schedule
- [x] `POST /api/v2/schedule/:id/result/` - set result json from schedule

**Comment by user404d** [comment]
#20
