### ISSUE TITLE
Communication with Gitlab: Native API or DbAPI?

### ISSUE THREAD

**Issue by russleyshaw** [siggame/coliselia#13]
How should the components (Ophelia & Colisee) communicate with GitLab?

Reasons to communicate directly with GitLab:
- Lots of work to implement a wrapper
- Is an API for an API necessary?

Reasons to communicate through DbApi
- Synchronizing Gitlab and Database will be easier (i.e. if a user is created, its populated in both areas)
- Single communication location
- Single authentication for DB & Gitlab

**Comment by renodubois** [comment]
So I think the DB API will be a bit more work but will be more worth it, since we will only have to deal with calling one API.

**Comment by LeaveItToBeaves** [comment]
I agree, I think all the points you made are very appealing and I think it will make it worth it in the long run.

**Comment by russleyshaw** [comment]
Going with DBApi interactions for now

**Comment by russleyshaw** [comment]
After some deeper investigation and thought experiments, communication between the two will be independent. One reason for this is because a GitLab user could potentially change his or her password and it not be reflected in the database. Becaause of this, they are two independent systems and should be treated as such.
