### ISSUE TITLE
Fix team and user dbapi routers

### ISSUE THREAD

**Issue by user404d** [siggame/coliselia#15]
Team and user routers are currently breaking the dbapi build.

**Comment by user404d** [comment]
http://knexjs.org/#Promises-then

**Comment by russleyshaw** [comment]
If this the asCallback methods, then I think we can ignore this. The code is transpiled regardless. This is a bug with knex typescript files.

Promises are annoying when you want to easily forward Sql data through to the response object.

**Comment by user404d** [comment]
See [these changes](https://github.com/siggame/coliselia/compare/fix_dbapi_users_and_teams)

Effectively the same, but typescript doesn't complain.
