### ISSUE TITLE
Team API Testing

### ISSUE THREAD

**Issue by russleyshaw** [siggame/coliselia#24]
Add tests to check normal and error/robustness cases for:

- [ ] GetTeams `/api/v2/team/`
- [ ] GetTeam `/api/v2/team/:id/`
- [ ] CreateTeam `POST /api/v2/team/`
- [ ] UpdateTeam `POST /api/v2/team/:id/`
- [ ] DeleteTeam `POST /api/v2/team/:id/delete`

**Comment by user404d** [comment]
`rip` - too soon
