### ISSUE TITLE
Pre-Configured GitLab and Management

### ISSUE THREAD

**Issue by russleyshaw** [siggame/coliselia#28]
File: `gitlab/base/*`

A script/system should be developed to allow us to distribute a base GitLab image. This would be useful because it would allow us to rely on pre-added users/tokens/repos etc. 

Most likely there will be some sort of image file that contains the preconfigured image (such as `base_gitlab.tar`)

Depending on Docker functionality the exact script features can be changed, but the basic idea is
- [x] Create new GitLab environment
- [x] Save current GitLab environment to file
- [x] Load file as current GitLab environment

**The script:**
- [x] Should create a "fresh" GitLab image as the base_docker image
- [x] Should load a previously exported image as the current base_docker image
- [x] Should run the current base_docker image as a container
- [x] Should save the base_docker container as an image
- [x] Should export/save base_docker image

### Other requirements
- Should prompt user `Are you sure? [y/N]` before applying any changes to exported GitLab file
- Update local README.md with specific information about preconfigured GitLab, such as usernames, passwords, tokens, etc

**Comment by russleyshaw** [comment]
Hints:
`docker save` does not save the file system
`docker export` does not export any docker metadata (such as CMD, exposed ports, etc)

**Comment by russleyshaw** [comment]
This might be a futile effort considering its incredibly likely we generate image files that are GB in size.
Most likely we will need to host them on the siggame@mst.edu Google Drive or on r99 and provide links to them in the README.

**Comment by user404d** [comment]
https://docs.docker.com/engine/tutorials/dockervolumes/#/backup-restore-or-migrate-data-volumes

I think this may be a way forward.

**Comment by russleyshaw** [comment]
Try it out. Currently there are 3 volumes used by GitLab to store data. I dont know if that is the entirety of the data that gitlab uses, but I can confirm that I can run gitlab multiple times with the same configuration. Of course the issue here is having it keep that configuration from a clean workspace. Maybe you can export those 3 volumes to 3 respective tar files.

**Comment by russleyshaw** [comment]
I think all of the gitlab specific information is contained between these three volumes

- VOLUME /etc/gitlab
- VOLUME /var/log/gitlab
- VOLUME /var/opt/gitlab

Try exporting these to .tars, then import them into a fresh GitLab image and see if changes persist.

**Comment by user404d** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/issues/14740

after googling around maybe this will be the thing we should do?

**Comment by russleyshaw** [comment]
I think a more docker specific approach might be better, and its basically doing the same thing as cloning the volumes because we know that should work since otherwise, a dockerized gitlab would not be able to survive reboots .

**Comment by user404d** [comment]
https://hub.docker.com/r/gitlab/gitlab-ce/~/dockerfile/
https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/docker/assets/wrapper

My current solution hooks into the post reconfigure 'hook' that this wrapper script has in it. This wrapper script is called every time that docker restarts the container so it is possible to restore restore backups fairly easily this way.

Maybe at the end of the day [this](https://github.com/mrak/stubby4node) is what we want anyways? This will make testing like 1000000x faster, since gitlab takes ~5 minutes to prop itself up even between warm restarts. This is due to the wrapper script literally remaking all the services every time that the container is restarted.

(I still haven't made that SO post... I want to exhaust all my options first. I'm close to giving up though).

**Comment by user404d** [comment]
http://docs.projectatomic.io/container-best-practices/#planning_storage

This seems like a good resource with good recommendations. I think reaching out on SO or some docker irc channel is going to be the best bet for a 'good' solution to this problem though.

**Comment by russleyshaw** [comment]
Crazy idea: use an actual VM (such as VirtualBox/Vagrant). Docker really isnt offering us anything right now in the realm of functionality for GitLab. 

What do you think? Or is the fluidity of docker-compose too important to give up just yet?

**Comment by russleyshaw** [comment]
Another idea:
Use `docker export` but manually begin the gitlab process

**Comment by russleyshaw** [comment]
Mainly completed by #31 PR additional features/bugs should be added individually
