### ISSUE TITLE
Swagger

### ISSUE THREAD

**Issue by russleyshaw** [siggame/coliselia#37]
Basically, we are going to manually end up doing everything that Swagger provides.

- Authentication
- Validation
- Endpoint exposure
- etc...

It basically uses JSON Schema underneath which is what we are directly using. 

I can't help but think that using Swagger would do most of the work for us and keep everything clean. I don't think it would be a lot of work to switch over anyways

**Comment by jonsimington** [comment]
i've heard good things about swagger.  was going to implement it at my project at work but didn't have the time to translate the api

**Comment by user404d** [comment]
Swagger looks good and if it will help to keep things maintainable/manageable then I'm all for it.

**Comment by russleyshaw** [comment]
Transitioning to Development

**Comment by russleyshaw** [comment]
Nevermind. We already have endpoints created and a verification process. This could be implemented in a later date but don't add much right now.
